// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Item() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col items-start justify-start h-auto pl-4 mx-0 mb-12 border-l border-transparent lg:w-1/3 lg:mb-0 lg:pl-8 lg:ml-8 lg:border-gray-200 min-w-80 max-w-96\"><div class=\"flex items-center justify-center w-full\"><div class=\"w-16 h-16 mr-4 overflow-hidden rounded-full\"><img src=\"https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=2547&amp;q=80\" class=\"object-cover w-full h-full\"></div><div class=\"flex flex-col items-start justify-center\"><h4 class=\"font-bold\">Jane Doe</h4><p class=\"text-gray-600\">Salu99999</p></div><div class=\"flex-auto max-w-64\"></div><div class=\"w-8 h-8 mr-4 overflow-hidden rounded-full \"><img src=\"/static/saludos.png\" class=\"object-cover w-full h-full\"></div></div><blockquote class=\"mt-8 text-lg text-gray-500\">\"Esperando tu saludos desde ayer\"</blockquote></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
