// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Sidebar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Sidebar --><div class=\"sidebar\" x-data=\"{ page: &#39;dashboard&#39;, toggle(page) { this.page = page } }\" hx-get=\"/dashboard\" hx-target=\"#scaffold\" hx-trigger=\"load\"><a href=\"#\" class=\"logo\"><div class=\"image bx\"><img class=\"rounded-full \" src=\"/static/favicon.ico\" alt=\"Favicon\"></div><div class=\"logo-name\"><span>Salu</span>dos</div></a><ul class=\"side-menu\"><li :class=\"page == &#39;dashboard&#39; ? &#39;active&#39; : &#39;&#39; \" hx-get=\"/dashboard\" hx-target=\"#scaffold\" x-on:click=\"toggle(&#39;dashboard&#39;)\"><a href=\"#\"><i class=\"bx bxs-dashboard\"></i>Dashboard</a></li><li :class=\"page == &#39;users&#39; ? &#39;active&#39; : &#39;&#39; \" hx-get=\"/users\" hx-target=\"#scaffold\" x-on:click=\"toggle(&#39;users&#39;)\"><a href=\"#\"><i class=\"bx bx-group\"></i>Users</a></li><li :class=\"page == &#39;settings&#39; ? &#39;active&#39; : &#39;&#39; \" hx-get=\"/settings\" hx-target=\"#scaffold\" x-on:click=\"toggle(&#39;settings&#39;)\"><a href=\"#\"><i class=\"bx bx-cog\"></i>Settings</a></li></ul><ul class=\"side-menu\"><li><a href=\"#\" class=\"logout\"><i class=\"bx bx-log-out-circle\"></i> Logout</a></li></ul></div><!-- End of Sidebar -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
